[project]
name = "sistema-academico-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.2",
    "sqlmodel>=0.0.27",
]

[dependency-groups]
dev = [
    "ipython>=9.7.0",
    "ruff>=0.14.5",
]
